name: railway_rail_wear_calculator
description: Railway Rail Wear Calculator prototype
publish_to: "none"
version: 0.1.1+2
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/nr4_gauge.jpg
    - assets/nr4_reference-1.jpg
    - assets/rail_reference.jpg
    - assets/train-horn-2 (1).mp3
